### ISSUE TITLE
make use of tables from ./output/scores for analysis notebooks?

### ISSUE THREAD

**Issue by gfudenberg** [Fudenberg-Research-Group/dynamic_extrusion_boundaries#10]
https://github.com/Fudenberg-Research-Group/dynamic_extrusion_boundaries/blob/main/analysis/sweeps_map_frips.ipynb

seems to use `file = pd.read_csv('inputs/data/fripscore_hres.csv')`. Could this instead make use of one of the tables in ./output/scores?

Also, can `directory='/project/fudenber_735/polychrom/Dynamic_boundary_model/1d_sims_dynamic_boundary/dynamical_boundary_simulations/sims/' #simulation directory` be deleted, as well as everything before cell [60] as that is where manuscript-related content appears to begin? Then this notebook could be renamed to something that could align nicely with the paper.

**Comment by hrahmanin** [comment]
I think previous cells are included in supplementary figures of manuscript.

**Comment by hrahmanin** [comment]
thanks; resolved.
