### ISSUE TITLE
contact_maps_visualization

### ISSUE THREAD

**Issue by gfudenberg** [Fudenberg-Research-Group/dynamic_extrusion_boundaries#11]
the maps in contact_maps_visualization do not seem that informative--
https://github.com/Fudenberg-Research-Group/dynamic_extrusion_boundaries/blob/main/analysis/contact_maps_visualization.ipynb

Is this file helpful to you or a manuscript reader? If so, perhaps better to display a contactmap with more evident features?

**Comment by hrahmanin** [comment]
Thanks; resolved.
