### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by Yaoyx** [Fudenberg-Research-Group/dynamic_extrusion_boundaries#12]
- [x]  It might be helpful to add an annotation behind each parameters, particularly, for some abbreviations. (e.g. what does "facestall" and "backstall" mean, and I guess 'LEF' means loop extrusion factor, 'replica' indicates one DNA sequence? )

https://github.com/Fudenberg-Research-Group/dynamic_extrusion_boundaries/blob/f40351f44153c62f3bdd01f5f645a1654db18463/scripts/simulations/simulation_1d.py#L19-L34

- [x]  For CTCF_right/left_sites, do they start from the center of one polymer chain?

- [x]  Does trajectory_length indicates how long extruder will need to pass through one monomer? https://github.com/Fudenberg-Research-Group/dynamic_extrusion_boundaries/blob/f40351f44153c62f3bdd01f5f645a1654db18463/scripts/simulations/simulation_1d.py#L77

- [x] make_translocator and its associated funcs look important to me.  Would it be better to go into engine folder?

- [x]  Should this be hardcoded with np.zeros? https://github.com/Fudenberg-Research-Group/dynamic_extrusion_boundaries/blob/f40351f44153c62f3bdd01f5f645a1654db18463/scripts/simulations/simulation_1d.py#L65-L66

- [x] I thought this 'less' operation is used for filtering at the beginning. An annotation says "the chance of a value falls within this range (0, occupancy/birthProb/...) reflects the probability" might be helpful.  https://github.com/Fudenberg-Research-Group/dynamic_extrusion_boundaries/blob/c819111ef4c4cd1599c74d47b63c4d149444fdad/scripts/simulations/engines/lattice_translocators.py#L178

- [x]  what does multiplying by 1 do here? https://github.com/Fudenberg-Research-Group/dynamic_extrusion_boundaries/blob/f40351f44153c62f3bdd01f5f645a1654db18463/scripts/simulations/simulation_1d.py#L132-L133

- [x]  The pathway need to be updated

https://github.com/Fudenberg-Research-Group/dynamic_extrusion_boundaries/blob/f40351f44153c62f3bdd01f5f645a1654db18463/scripts/simulations/simulation_1d.py#L9

- [x]  Might be helpful to mention paramdict is input as kwargs. https://github.com/Fudenberg-Research-Group/dynamic_extrusion_boundaries/blob/aa27bba3f1b2d121b1c5b6368c8da2aaef83d8e4/scripts/simulations/utils/funcs.py#L81-L85
- [x] CTCF_sites and CTCF_positions are a bit confusing as they are very similar. motif_sites and protein_position might be more distinguishable. https://github.com/Fudenberg-Research-Group/dynamic_extrusion_boundaries/blob/f40351f44153c62f3bdd01f5f645a1654db18463/scripts/simulations/simulation_1d.py#L99-L119

- [x]  Should LEF_arrays have the same order as __init__  in translocator, as it takes in positional arguments? https://github.com/Fudenberg-Research-Group/dynamic_extrusion_boundaries/blob/b69af4ff213aa5b2983dd7fe2485a1bac8476fd3/scripts/simulations/utils/funcs.py#L79 https://github.com/Fudenberg-Research-Group/dynamic_extrusion_boundaries/blob/b69af4ff213aa5b2983dd7fe2485a1bac8476fd3/scripts/simulations/utils/funcs.py#L109 https://github.com/Fudenberg-Research-Group/dynamic_extrusion_boundaries/blob/c819111ef4c4cd1599c74d47b63c4d149444fdad/scripts/simulations/engines/lattice_translocators.py#L133-L143

- [x] For paramdict_to_filename(), instead of put all params in the filename, maybe a metadata table can be an option, so filename can just be row index
- [x] #17
![image](https://github.com/user-attachments/assets/018d4d7d-4b66-4270-9eab-4b7a0d707cf1)
![image](https://github.com/user-attachments/assets/2f858c77-dc52-48fc-921e-bc718045b928)
https://github.com/Fudenberg-Research-Group/dynamic_extrusion_boundaries/blob/f40351f44153c62f3bdd01f5f645a1654db18463/analysis/contact_maps_visualization.ipynb

- [ ] 

[Editing...]

**Comment by hrahmanin** [comment]
@Yaoyx Thanks for the comments. I am responding some of them inline:

- For CTCF_right/left_sites, do they start from the center of one polymer chain?
                 That starts from the first lattice site from one end of the polymer. 
- Does trajectory_length indicates how long extruder will need to pass through one monomer?
                 That is the simulation trajectory length (time duration of simulation), which is how many times the whole system is updated.
- CTCF_sites and CTCF_positions are a bit confusing as they are very similar. motif_sites and protein_position might be more distinguishable.
                    Nice idea. For now because both of them are the same, I just kept CTCF_sites. 
- make_translocator and its associated funcs look important to me. Would it be better to go into engine folder? It can be an option. @gfudenberg  do you have any preference?
I am resolving the rest ...

**Comment by Yaoyx** [comment]
> That is the simulation trajectory length (time duration of simulation), which is how many times the whole system is updated.

Ah I see, so for example the shape here (trajectory_length, len(CTCF_sites_right), 1) for each CTCF site, the system will update "trajectory_length" this amount of steps.

https://github.com/Fudenberg-Research-Group/dynamic_extrusion_boundaries/blob/f40351f44153c62f3bdd01f5f645a1654db18463/scripts/simulations/simulation_1d.py#L112-L115

**Comment by hrahmanin** [comment]
Regarding
 'Should LEF_arrays have the same order as init in translocator, as it takes in positional arguments?'
It seems that this is related to branch 'f40351f', which might be an old branch. However, in main branch there are in the same order.
