### ISSUE TITLE
missing condition for Justice FRiP

### ISSUE THREAD

**Issue by gfudenberg** [Fudenberg-Research-Group/dynamic_extrusion_boundaries#8]
https://github.com/Fudenberg-Research-Group/dynamic_extrusion_boundaries/blob/f40351f44153c62f3bdd01f5f645a1654db18463/inputs/experiments/experimental_data_table.txt#L5

also missing decimal point in line 7?

**Comment by hrahmanin** [comment]
resolved; thanks.
