### ISSUE TITLE
unused imports?

### ISSUE THREAD

**Issue by gfudenberg** [Fudenberg-Research-Group/dynamic_extrusion_boundaries#9]
https://github.com/Fudenberg-Research-Group/dynamic_extrusion_boundaries/blob/f40351f44153c62f3bdd01f5f645a1654db18463/scripts/simulations/simulation_md.py#L24

more unused imports: 
https://github.com/Fudenberg-Research-Group/dynamic_extrusion_boundaries/blob/f40351f44153c62f3bdd01f5f645a1654db18463/scripts/processing/maps.py#L19

**Comment by gfudenberg** [comment]
also would be nice to remove DS_Store files from the repository

**Comment by hrahmanin** [comment]
Thanks; resolved.
